package Vista;

import Modelo.Empleados;
import Modelo.EmpleadosDAO;
import Modelo.Nomina;
import Modelo.NominaDAO;
import Modelo.Permisos;
import Modelo.PermisosDAO;
import com.itextpdf.text.Chunk;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.sun.jdi.connect.spi.Connection;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;

/**
 *
 * @author EDER
 */
public class SGE extends javax.swing.JFrame {

    Empleados em = new Empleados();
    EmpleadosDAO emp = new EmpleadosDAO();
    Nomina nm = new Nomina();
    NominaDAO nom = new NominaDAO();
    Permisos pm = new Permisos();
    PermisosDAO pem = new PermisosDAO();
    DefaultTableModel modelo = new DefaultTableModel();
    PreparedStatement ps;
    ResultSet rs;

    /**
     * Creates new form SGE
     */
    public SGE() {
        initComponents();
        this.setLocationRelativeTo(null);
        IDnume.setVisible(false);
        IdPay.setVisible(false);
        IdPerms.setVisible(false);
    }

    public void ListarEmpleados() {

        List<Empleados> ListarEm = emp.ListarEmpleados();
        modelo = (DefaultTableModel) jTableresgistrar.getModel();
        Object[] ob = new Object[10];

        for (int i = 0; i < ListarEm.size(); i++) {

            ob[0] = ListarEm.get(i).getId();
            ob[1] = ListarEm.get(i).getName();
            ob[2] = ListarEm.get(i).getIden();
            ob[3] = ListarEm.get(i).getPhone();
            ob[4] = ListarEm.get(i).getEmail();
            ob[5] = ListarEm.get(i).getAddress();
            ob[6] = ListarEm.get(i).getJob();
            ob[7] = ListarEm.get(i).getHire();
            ob[8] = ListarEm.get(i).getStart();
            ob[9] = ListarEm.get(i).getEnd();
            modelo.addRow(ob);
        }

        jTableresgistrar.setModel(modelo);
    }

    public void ListarNomina() {

        List<Nomina> ListaNm = nom.ListarNomina();
        modelo = (DefaultTableModel) PAYjTable2.getModel();
        Object[] ob = new Object[7];

        for (int i = 0; i < ListaNm.size(); i++) {

            ob[0] = ListaNm.get(i).getName();
            ob[1] = ListaNm.get(i).getIden();
            ob[2] = ListaNm.get(i).getJob();
            ob[3] = ListaNm.get(i).getSalary();
            ob[4] = ListaNm.get(i).getCommissions();
            ob[5] = ListaNm.get(i).getBonuses();
            ob[6] = ListaNm.get(i).getTotal();
            modelo.addRow(ob);

        }

        PAYjTable2.setModel(modelo);

    }

    public void ListarPermisos() {

        List<Permisos> ListaPm = pem.ListarPermisos();
        modelo = (DefaultTableModel) PERMSjTable3.getModel();
        Object[] ob = new Object[5];

        for (int i = 0; i < ListaPm.size(); i++) {

            ob[0] = ListaPm.get(i).getName();
            ob[1] = ListaPm.get(i).getIden();
            ob[2] = ListaPm.get(i).getJob();
            ob[3] = ListaPm.get(i).getType();
            ob[4] = ListaPm.get(i).getDescription();
            modelo.addRow(ob);

        }

        PERMSjTable3.setModel(modelo);

    }

    public void LimpiarTable() {

        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    public void BuscarEmpleados(String buscar) {

        EmpleadosDAO EDAO = new EmpleadosDAO();
        DefaultTableModel modelo = EDAO.BuscarEmpleados(buscar);

        jTableresgistrar.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTabbedStaff = new javax.swing.JTabbedPane();
        jPanelStaff = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombreEmpleados = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIDEmpleados = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTelefonoEmpleados = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCorreoEmpleados = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDireccionEmpleados = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCargoEmpleados = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldContratacionEmpleados = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldEntradaEmpleados = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldSalidaEmpleados = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableresgistrar = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtBuscarE = new javax.swing.JTextField();
        CREATEjButton4 = new javax.swing.JButton();
        UPDATEjButton5 = new javax.swing.JButton();
        DELETEjButton6 = new javax.swing.JButton();
        IDnume = new javax.swing.JTextField();
        jPanelPay = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        NAME_PAYjTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ID_PAYjTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        JOB_PAYjTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        SALARY_PAYjTextField14 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        COM_PAYjTextField15 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        BONUS_PAYjTextField16 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        STOTAL_PAYjTextField17 = new javax.swing.JTextField();
        CALCULATEjButton7 = new javax.swing.JButton();
        CREATE_PAYjButton8 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        PAYjTable2 = new javax.swing.JTable();
        PRINT_PAYjButton9 = new javax.swing.JButton();
        DELETE_PAYjButton4 = new javax.swing.JButton();
        IdPay = new javax.swing.JTextField();
        jPanelPermis = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        NAME_PERMSjTextField18 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ID_PERMSTextField19 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        JOB_PERMSjTextField20 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        TYPE_PERMSjTextField21 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        DESCRjTextField22 = new javax.swing.JTextField();
        CREATEj_PERMSButton10 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        PRINT_PERMSjButton11 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        PERMSjTable3 = new javax.swing.JTable();
        DELETE_PERMSjButton5 = new javax.swing.JButton();
        IdPerms = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoEMS 170px.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 150));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 150));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 150));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("STAFF");
        jButton1.setMaximumSize(new java.awt.Dimension(105, 24));
        jButton1.setMinimumSize(new java.awt.Dimension(105, 24));
        jButton1.setPreferredSize(new java.awt.Dimension(105, 24));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("PAY");
        jButton2.setMaximumSize(new java.awt.Dimension(100, 24));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 24));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 24));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("PERMS");
        jButton3.setMaximumSize(new java.awt.Dimension(100, 24));
        jButton3.setMinimumSize(new java.awt.Dimension(100, 24));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 24));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 263, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 720));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMPLOYEE MANAGEMENT SYSTEM");

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("EXIT");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LOG OUT");
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 1130, 150));

        jLabel3.setText("Name:");

        jTextFieldNombreEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel4.setText("ID:");

        jLabel5.setText("Phone:");

        jTextFieldTelefonoEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoEmpleadosActionPerformed(evt);
            }
        });

        jLabel6.setText("Email:");

        jTextFieldCorreoEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoEmpleadosActionPerformed(evt);
            }
        });

        jLabel7.setText("Address:");

        jLabel8.setText("Job title:");

        jTextFieldCargoEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCargoEmpleadosActionPerformed(evt);
            }
        });

        jLabel9.setText("Hire date:");

        jTextFieldContratacionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContratacionEmpleadosActionPerformed(evt);
            }
        });

        jLabel10.setText("Start date:");

        jLabel11.setText("End date:");

        jTableresgistrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Name", "Iden", "Phone", "Email", "Address", "Job", "Hire Date", "Start Date", "End Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableresgistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableresgistrarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableresgistrar);
        if (jTableresgistrar.getColumnModel().getColumnCount() > 0) {
            jTableresgistrar.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        jLabel12.setText("Search:");

        txtBuscarE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarEKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarEKeyReleased(evt);
            }
        });

        CREATEjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CreateICOn.png"))); // NOI18N
        CREATEjButton4.setMaximumSize(new java.awt.Dimension(28, 28));
        CREATEjButton4.setMinimumSize(new java.awt.Dimension(28, 28));
        CREATEjButton4.setPreferredSize(new java.awt.Dimension(28, 28));
        CREATEjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEjButton4ActionPerformed(evt);
            }
        });

        UPDATEjButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UpdateICON.png"))); // NOI18N
        UPDATEjButton5.setMaximumSize(new java.awt.Dimension(28, 28));
        UPDATEjButton5.setMinimumSize(new java.awt.Dimension(28, 28));
        UPDATEjButton5.setPreferredSize(new java.awt.Dimension(28, 28));
        UPDATEjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEjButton5ActionPerformed(evt);
            }
        });

        DELETEjButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DeleteICON.png"))); // NOI18N
        DELETEjButton6.setMaximumSize(new java.awt.Dimension(28, 28));
        DELETEjButton6.setMinimumSize(new java.awt.Dimension(28, 28));
        DELETEjButton6.setPreferredSize(new java.awt.Dimension(28, 28));
        DELETEjButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEjButton6ActionPerformed(evt);
            }
        });

        IDnume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDnumeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStaffLayout = new javax.swing.GroupLayout(jPanelStaff);
        jPanelStaff.setLayout(jPanelStaffLayout);
        jPanelStaffLayout.setHorizontalGroup(
            jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStaffLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(IDnume, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStaffLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 133, Short.MAX_VALUE))
                    .addGroup(jPanelStaffLayout.createSequentialGroup()
                        .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelStaffLayout.createSequentialGroup()
                                .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldCargoEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldNombreEmpleados, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldContratacionEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldIDEmpleados, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel9))
                                .addGap(62, 62, 62)
                                .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelStaffLayout.createSequentialGroup()
                                        .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldEntradaEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldTelefonoEmpleados, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(63, 63, 63)
                                        .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextFieldSalidaEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldCorreoEmpleados, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLabel11)))
                                    .addComponent(jLabel10))
                                .addGap(60, 60, 60)
                                .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDireccionEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanelStaffLayout.createSequentialGroup()
                                        .addComponent(CREATEjButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UPDATEjButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DELETEjButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelStaffLayout.setVerticalGroup(
            jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStaffLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStaffLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSalidaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEntradaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldContratacionEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCargoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelStaffLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombreEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIDEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTelefonoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCorreoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDireccionEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDnume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStaffLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(CREATEjButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStaffLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DELETEjButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UPDATEjButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedStaff.addTab("Staff", jPanelStaff);

        jLabel13.setText("Name:");

        NAME_PAYjTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME_PAYjTextField11ActionPerformed(evt);
            }
        });

        jLabel14.setText("ID:");

        jLabel15.setText("Job title:");

        jLabel16.setText("Salary:");

        SALARY_PAYjTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALARY_PAYjTextField14ActionPerformed(evt);
            }
        });

        jLabel17.setText("Commissions:");

        COM_PAYjTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COM_PAYjTextField15ActionPerformed(evt);
            }
        });

        jLabel18.setText("Bonuses:");

        BONUS_PAYjTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BONUS_PAYjTextField16ActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        STOTAL_PAYjTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STOTAL_PAYjTextField17ActionPerformed(evt);
            }
        });

        CALCULATEjButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CalculateICON.png"))); // NOI18N
        CALCULATEjButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULATEjButton7ActionPerformed(evt);
            }
        });

        CREATE_PAYjButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CreateICOn.png"))); // NOI18N
        CREATE_PAYjButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATE_PAYjButton8ActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        PAYjTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Job Title", "Salary", "Commissions", "Bonuses", "Total"
            }
        ));
        PAYjTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PAYjTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(PAYjTable2);

        PRINT_PAYjButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PrintICON.png"))); // NOI18N
        PRINT_PAYjButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRINT_PAYjButton9ActionPerformed(evt);
            }
        });

        DELETE_PAYjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DeleteICON.png"))); // NOI18N
        DELETE_PAYjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETE_PAYjButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPayLayout = new javax.swing.GroupLayout(jPanelPay);
        jPanelPay.setLayout(jPanelPayLayout);
        jPanelPayLayout.setHorizontalGroup(
            jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPayLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(IdPay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelPayLayout.createSequentialGroup()
                        .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NAME_PAYjTextField11)
                            .addComponent(ID_PAYjTextField12)
                            .addComponent(JOB_PAYjTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(151, 151, 151)
                        .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SALARY_PAYjTextField14)
                            .addComponent(jLabel17)
                            .addComponent(COM_PAYjTextField15)
                            .addComponent(jLabel18)
                            .addComponent(BONUS_PAYjTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(147, 147, 147)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(STOTAL_PAYjTextField17)
                            .addComponent(CALCULATEjButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CREATE_PAYjButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PRINT_PAYjButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(DELETE_PAYjButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanelPayLayout.setVerticalGroup(
            jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPayLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanelPayLayout.createSequentialGroup()
                        .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPayLayout.createSequentialGroup()
                                .addComponent(STOTAL_PAYjTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CALCULATEjButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CREATE_PAYjButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PRINT_PAYjButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DELETE_PAYjButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPayLayout.createSequentialGroup()
                                .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NAME_PAYjTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SALARY_PAYjTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ID_PAYjTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(COM_PAYjTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JOB_PAYjTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BONUS_PAYjTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPayLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPayLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IdPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))))
        );

        jTabbedStaff.addTab("Pay", jPanelPay);

        jLabel19.setText("Name:");

        jLabel20.setText("ID:");

        jLabel21.setText("Job title:");

        JOB_PERMSjTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOB_PERMSjTextField20ActionPerformed(evt);
            }
        });

        jLabel22.setText("Permissions type:");

        jLabel23.setText("Description:");

        CREATEj_PERMSButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CreateICOn.png"))); // NOI18N
        CREATEj_PERMSButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEj_PERMSButton10ActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        PRINT_PERMSjButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PrintICON.png"))); // NOI18N
        PRINT_PERMSjButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRINT_PERMSjButton11ActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        PERMSjTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Job", "Permissions Type", "Description"
            }
        ));
        PERMSjTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PERMSjTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(PERMSjTable3);

        DELETE_PERMSjButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DeleteICON.png"))); // NOI18N
        DELETE_PERMSjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETE_PERMSjButton5ActionPerformed(evt);
            }
        });

        IdPerms.setText("0");

        javax.swing.GroupLayout jPanelPermisLayout = new javax.swing.GroupLayout(jPanelPermis);
        jPanelPermis.setLayout(jPanelPermisLayout);
        jPanelPermisLayout.setHorizontalGroup(
            jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPermisLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(IdPerms, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPermisLayout.createSequentialGroup()
                        .addGroup(jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NAME_PERMSjTextField18)
                            .addComponent(ID_PERMSTextField19, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(136, 136, 136)
                        .addGroup(jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JOB_PERMSjTextField20, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(TYPE_PERMSjTextField21)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(136, 136, 136)
                        .addGroup(jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DESCRjTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(89, 89, 89)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DELETE_PERMSjButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PRINT_PERMSjButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(CREATEj_PERMSButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanelPermisLayout.setVerticalGroup(
            jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPermisLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPermisLayout.createSequentialGroup()
                        .addGroup(jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPermisLayout.createSequentialGroup()
                                .addComponent(CREATEj_PERMSButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PRINT_PERMSjButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DELETE_PERMSjButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPermisLayout.createSequentialGroup()
                                .addGroup(jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NAME_PERMSjTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JOB_PERMSjTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DESCRjTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ID_PERMSTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TYPE_PERMSjTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanelPermisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPermisLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPermisLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(IdPerms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedStaff.addTab("Perms", jPanelPermis);

        getContentPane().add(jTabbedStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 1130, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LimpiarTable();
        ListarEmpleados();
        jTabbedStaff.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        LimpiarTable();
        ListarPermisos();
        jTabbedStaff.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldTelefonoEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoEmpleadosActionPerformed

    private void jTextFieldCargoEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCargoEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCargoEmpleadosActionPerformed

    private void jTextFieldCorreoEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoEmpleadosActionPerformed

    private void CREATEjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEjButton4ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(jTextFieldNombreEmpleados.getText()) && !"".equals(jTextFieldIDEmpleados.getText()) && !"".equals(jTextFieldTelefonoEmpleados.getText()) && !"".equals(jTextFieldCorreoEmpleados.getText()) && !"".equals(jTextFieldDireccionEmpleados.getText()) && !"".equals(jTextFieldCargoEmpleados.getText()) && !"".equals(jTextFieldContratacionEmpleados.getText()) && !"".equals(jTextFieldEntradaEmpleados.getText()) && !"".equals(jTextFieldSalidaEmpleados.getText())) {

            em.setName(jTextFieldNombreEmpleados.getText());
            em.setIden(Integer.parseInt(jTextFieldIDEmpleados.getText()));
            em.setPhone(Integer.parseInt(jTextFieldTelefonoEmpleados.getText()));
            em.setEmail(jTextFieldCorreoEmpleados.getText());
            em.setAddress(jTextFieldDireccionEmpleados.getText());
            em.setJob(jTextFieldCargoEmpleados.getText());
            em.setHire(jTextFieldContratacionEmpleados.getText());
            em.setStart(jTextFieldEntradaEmpleados.getText());
            em.setEnd(jTextFieldSalidaEmpleados.getText());

            emp.RegistrarEmpleados(em);
            LimpiarTable();
            LimpiarEmpleados();
            ListarEmpleados();
            JOptionPane.showMessageDialog(null, "REGISTERED EMPLOYEE");

        } else {
            JOptionPane.showMessageDialog(null, "EMPTY FIELD");
        }
    }//GEN-LAST:event_CREATEjButton4ActionPerformed

    private void UPDATEjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEjButton5ActionPerformed
        // TODO add your handling code here:
        if ("".equals(IDnume.getText())) {

            JOptionPane.showMessageDialog(null, "SELECT A ROW");

        } else {

            if (!"".equals(jTextFieldNombreEmpleados.getText()) && !"".equals(jTextFieldIDEmpleados.getText()) && !"".equals(jTextFieldTelefonoEmpleados.getText()) && !"".equals(jTextFieldCorreoEmpleados.getText()) && !"".equals(jTextFieldDireccionEmpleados.getText()) && !"".equals(jTextFieldCargoEmpleados.getText()) && !"".equals(jTextFieldContratacionEmpleados.getText()) && !"".equals(jTextFieldEntradaEmpleados.getText()) && !"".equals(jTextFieldSalidaEmpleados.getText())) {

                em.setName(jTextFieldNombreEmpleados.getText()); // se le ingresaran los datos
                em.setIden(Integer.parseInt(jTextFieldIDEmpleados.getText()));
                em.setPhone(Integer.parseInt(jTextFieldTelefonoEmpleados.getText()));
                em.setEmail(jTextFieldCorreoEmpleados.getText());
                em.setAddress(jTextFieldDireccionEmpleados.getText());
                em.setJob(jTextFieldCargoEmpleados.getText());
                em.setHire(jTextFieldContratacionEmpleados.getText());
                em.setStart(jTextFieldEntradaEmpleados.getText());
                em.setEnd(jTextFieldSalidaEmpleados.getText());
                em.setId(Integer.parseInt(IDnume.getText()));

                emp.ModificarEmpleados(em);
                LimpiarTable();
                LimpiarEmpleados();
                ListarEmpleados();

            } else {
                JOptionPane.showMessageDialog(null, "THE FIELDS ARE EMPTY");
            }

        }
    }//GEN-LAST:event_UPDATEjButton5ActionPerformed

    private void DELETEjButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEjButton6ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(IDnume.getText())) {

            int pregunta = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO DELETE?");
            if (pregunta == 0) {
                int id = Integer.parseInt(IDnume.getText());
                emp.EliminarEmpleados(id);
                LimpiarTable();
                LimpiarEmpleados();
                ListarEmpleados();
            }
        } else {

            JOptionPane.showMessageDialog(null, "SELECT A ROW");

        }
    }//GEN-LAST:event_DELETEjButton6ActionPerformed

    private void jTextFieldContratacionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContratacionEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContratacionEmpleadosActionPerformed

    private void SALARY_PAYjTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALARY_PAYjTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SALARY_PAYjTextField14ActionPerformed

    private void COM_PAYjTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COM_PAYjTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COM_PAYjTextField15ActionPerformed

    private void BONUS_PAYjTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BONUS_PAYjTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BONUS_PAYjTextField16ActionPerformed

    private void CALCULATEjButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULATEjButton7ActionPerformed
        // TODO add your handling code here
        CALCULATEjButton7.addActionListener(e -> {

            int basesalary = Integer.parseInt(SALARY_PAYjTextField14.getText());
            int commi = Integer.parseInt(COM_PAYjTextField15.getText());
            int bon = Integer.parseInt(BONUS_PAYjTextField16.getText());

            int totalsalary = basesalary + commi + bon;

            STOTAL_PAYjTextField17.setText(String.valueOf(totalsalary));

        });


    }//GEN-LAST:event_CALCULATEjButton7ActionPerformed

    private void CREATE_PAYjButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATE_PAYjButton8ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(NAME_PAYjTextField11) && !"".equals(ID_PAYjTextField12) && !"".equals(JOB_PAYjTextField13) && !"".equals(SALARY_PAYjTextField14) && !"".equals(COM_PAYjTextField15) && !"".equals(BONUS_PAYjTextField16) && !"".equals(STOTAL_PAYjTextField17)) {

            nm.setName(NAME_PAYjTextField11.getText());
            nm.setIden(Integer.parseInt(ID_PAYjTextField12.getText()));
            nm.setJob(JOB_PAYjTextField13.getText());
            nm.setSalary(Integer.parseInt(SALARY_PAYjTextField14.getText()));
            nm.setCommissions(Integer.parseInt(COM_PAYjTextField15.getText()));
            nm.setBonuses(Integer.parseInt(BONUS_PAYjTextField16.getText()));
            nm.setTotal(Integer.parseInt(STOTAL_PAYjTextField17.getText()));
            nom.RegistrarNomina(nm);
            LimpiarTable();
            LimpiarNomina();
            ListarNomina();
            JOptionPane.showMessageDialog(null, "REGISTERED PAYROLL");

        } else {

            JOptionPane.showMessageDialog(null, "EMPTY FIELDS");

        }

    }//GEN-LAST:event_CREATE_PAYjButton8ActionPerformed

    private void STOTAL_PAYjTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STOTAL_PAYjTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STOTAL_PAYjTextField17ActionPerformed

    private void PRINT_PAYjButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRINT_PAYjButton9ActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();

        try {

            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Downloads/Reporte Nómina.pdf"));
            documento.open();

            Paragraph texto = new Paragraph("Estimado empleado,\n\n"
                    + "Nos complace informarte que tu solicitud de nómina ha sido aprobada. Los fondos solicitados serán depositados en tu cuenta según lo solicitado. Agradecemos tu diligencia en la presentación de la solicitud y confiamos en que estos fondos serán utilizados de manera responsable.\n\n"
                    + "Para cualquier pregunta o aclaración adicional, no dudes en contactar con el departamento de recursos humanos.\n\n"
                    + "Atentamente,\n\n"
                    + "Colpetro S.A.S.");

            texto.setAlignment(Element.ALIGN_JUSTIFIED);
            documento.add(texto);

            documento.add(Chunk.NEWLINE);

            PdfPTable tabla = new PdfPTable(7);
            tabla.addCell("Nombre");
            tabla.addCell("Cédula");
            tabla.addCell("Cargo");
            tabla.addCell("Salario");
            tabla.addCell("Comisiones");
            tabla.addCell("Bonificaciones");
            tabla.addCell("Salario Total");

            try {

                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ems?serverTimezone=UTC", "root", "");
                ps = con.prepareStatement("SELECT * FROM nomina");
                rs = ps.executeQuery();

                if (rs.next()) {

                    do {

                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        tabla.addCell(rs.getString(5));
                        tabla.addCell(rs.getString(6));
                        tabla.addCell(rs.getString(7));
                        tabla.addCell(rs.getString(8));

                    } while (rs.next());
                    documento.add(tabla);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
            documento.close();
            JOptionPane.showMessageDialog(null, "GENERATED REPORT#");
        } catch (Exception e) {
            e.printStackTrace();

        }


    }//GEN-LAST:event_PRINT_PAYjButton9ActionPerformed

    private void JOB_PERMSjTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOB_PERMSjTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JOB_PERMSjTextField20ActionPerformed

    private void CREATEj_PERMSButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEj_PERMSButton10ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(NAME_PERMSjTextField18) && !"".equals(ID_PERMSTextField19) && !"".equals(JOB_PERMSjTextField20) && !"".equals(TYPE_PERMSjTextField21) && !"".equals(DESCRjTextField22)) {

            pm.setName(NAME_PERMSjTextField18.getText());
            pm.setIden(Integer.parseInt(ID_PERMSTextField19.getText()));
            pm.setJob(JOB_PERMSjTextField20.getText());
            pm.setType(TYPE_PERMSjTextField21.getText());
            pm.setDescription(DESCRjTextField22.getText());
            pem.RegistrarPermisos(pm);
            LimpiarTable();
            LimpiarPermisos();
            ListarPermisos();
            JOptionPane.showMessageDialog(null, "REGISTERED PAYROLL");

        } else {

            JOptionPane.showMessageDialog(null, "EMPTY FIELDS");

        }


    }//GEN-LAST:event_CREATEj_PERMSButton10ActionPerformed

    private void PRINT_PERMSjButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRINT_PERMSjButton11ActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();

        try {

            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Downloads/Reporte Permiso.pdf"));
            documento.open();

            Paragraph texto = new Paragraph("Estimado empleado,\n\n"
                    + "Nos complace informarte que tu solicitud de permiso para ausentarte del trabajo ha sido aprobada. Reconocemos la importancia de atender asuntos personales y estamos comprometidos a apoyarte en tus necesidades fuera del ámbito laboral.\n\n"
                    + "Durante tu ausencia, confiamos en que has coordinado adecuadamente con tu equipo para asegurar una transición sin contratiempos y garantizar la continuidad de las operaciones. Te recordamos la importancia de mantenernos informados sobre cualquier situación que requiera nuestra atención durante tu ausencia.\n\n"
                    + "Apreciamos tu dedicación y compromiso con la empresa y confiamos en que regresarás renovado y listo para continuar contribuyendo al éxito de nuestro equipo.\n\n"
                    + "¡Que disfrutes de tu tiempo fuera!\n\n"
                    + "Atentamente,\n\n"
                    + "Colpetro S.A.S.");

            texto.setAlignment(Element.ALIGN_JUSTIFIED);
            documento.add(texto);

            documento.add(Chunk.NEWLINE);

            PdfPTable tabla = new PdfPTable(5);
            tabla.addCell("Nombre");
            tabla.addCell("Cédula");
            tabla.addCell("Cargo");
            tabla.addCell("Tipo de permiso");
            tabla.addCell("Descripción");

            try {

                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ems?serverTimezone=UTC", "root", "");
                ps = con.prepareStatement("SELECT * FROM permisos");
                rs = ps.executeQuery();

                if (rs.next()) {

                    do {

                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        tabla.addCell(rs.getString(5));
                        tabla.addCell(rs.getString(6));

                    } while (rs.next());
                    documento.add(tabla);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
            documento.close();
            JOptionPane.showMessageDialog(null, "GENERATED REPORT#");
        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_PRINT_PERMSjButton11ActionPerformed

    private void NAME_PAYjTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME_PAYjTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME_PAYjTextField11ActionPerformed

    private void DELETE_PAYjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETE_PAYjButton4ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(ID_PAYjTextField12.getText())) {

            int pregunta = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO DELETE?");
            if (pregunta == 0) {

                int id = Integer.parseInt(ID_PAYjTextField12.getText());
                nom.EliminarNomina(id);
                LimpiarTable();
                LimpiarNomina();
                ListarNomina();

            }

        } else {

            JOptionPane.showMessageDialog(null, "SELECT A ROW");

        }

    }//GEN-LAST:event_DELETE_PAYjButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LimpiarTable();
        ListarNomina();
        jTabbedStaff.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PAYjTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAYjTable2MouseClicked
        // TODO add your handling code here:
        int fila = PAYjTable2.rowAtPoint(evt.getPoint());
        NAME_PAYjTextField11.setText(PAYjTable2.getValueAt(fila, 0).toString());
        ID_PAYjTextField12.setText(PAYjTable2.getValueAt(fila, 1).toString());
        JOB_PAYjTextField13.setText(PAYjTable2.getValueAt(fila, 2).toString());
        SALARY_PAYjTextField14.setText(PAYjTable2.getValueAt(fila, 3).toString());
        COM_PAYjTextField15.setText(PAYjTable2.getValueAt(fila, 4).toString());
        BONUS_PAYjTextField16.setText(PAYjTable2.getValueAt(fila, 5).toString());
        STOTAL_PAYjTextField17.setText(PAYjTable2.getValueAt(fila, 6).toString());

    }//GEN-LAST:event_PAYjTable2MouseClicked

    private void jTableresgistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableresgistrarMouseClicked
        // TODO add your handling code here:
        int fila = jTableresgistrar.rowAtPoint(evt.getPoint());
        IDnume.setText(jTableresgistrar.getValueAt(fila, 0).toString());
        jTextFieldNombreEmpleados.setText(jTableresgistrar.getValueAt(fila, 1).toString());
        jTextFieldIDEmpleados.setText(jTableresgistrar.getValueAt(fila, 2).toString());
        jTextFieldTelefonoEmpleados.setText(jTableresgistrar.getValueAt(fila, 3).toString());
        jTextFieldCorreoEmpleados.setText(jTableresgistrar.getValueAt(fila, 4).toString());
        jTextFieldDireccionEmpleados.setText(jTableresgistrar.getValueAt(fila, 5).toString());
        jTextFieldCargoEmpleados.setText(jTableresgistrar.getValueAt(fila, 6).toString());
        jTextFieldContratacionEmpleados.setText(jTableresgistrar.getValueAt(fila, 7).toString());
        jTextFieldEntradaEmpleados.setText(jTableresgistrar.getValueAt(fila, 8).toString());
        jTextFieldSalidaEmpleados.setText(jTableresgistrar.getValueAt(fila, 9).toString());
    }//GEN-LAST:event_jTableresgistrarMouseClicked

    private void txtBuscarEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarEKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtBuscarEKeyPressed

    private void txtBuscarEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarEKeyReleased
        // TODO add your handling code here:
        BuscarEmpleados(txtBuscarE.getText());
    }//GEN-LAST:event_txtBuscarEKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void IDnumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDnumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDnumeActionPerformed

    private void DELETE_PERMSjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETE_PERMSjButton5ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(ID_PERMSTextField19.getText())) {

            int pregunta = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO DELETE?");
            if (pregunta == 0) {

                int id = Integer.parseInt(ID_PERMSTextField19.getText());
                pem.EliminarPermisos(id);
                LimpiarTable();
                LimpiarPermisos();
                ListarPermisos();
            }

        } else {

            JOptionPane.showMessageDialog(null, "SELECT A ROW");

        }

    }//GEN-LAST:event_DELETE_PERMSjButton5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Login v1 = new Login();
        v1.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void PERMSjTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PERMSjTable3MouseClicked
        // TODO add your handling code here:
        int fila = PERMSjTable3.rowAtPoint(evt.getPoint());
        NAME_PERMSjTextField18.setText(PERMSjTable3.getValueAt(fila, 0).toString());
        ID_PERMSTextField19.setText(PERMSjTable3.getValueAt(fila, 1).toString());
        JOB_PERMSjTextField20.setText(PERMSjTable3.getValueAt(fila, 2).toString());
        TYPE_PERMSjTextField21.setText(PERMSjTable3.getValueAt(fila, 3).toString());
        DESCRjTextField22.setText(PERMSjTable3.getValueAt(fila, 4).toString());

    }//GEN-LAST:event_PERMSjTable3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BONUS_PAYjTextField16;
    private javax.swing.JButton CALCULATEjButton7;
    private javax.swing.JTextField COM_PAYjTextField15;
    private javax.swing.JButton CREATE_PAYjButton8;
    private javax.swing.JButton CREATEjButton4;
    private javax.swing.JButton CREATEj_PERMSButton10;
    private javax.swing.JButton DELETE_PAYjButton4;
    private javax.swing.JButton DELETE_PERMSjButton5;
    private javax.swing.JButton DELETEjButton6;
    private javax.swing.JTextField DESCRjTextField22;
    private javax.swing.JTextField ID_PAYjTextField12;
    private javax.swing.JTextField ID_PERMSTextField19;
    private javax.swing.JTextField IDnume;
    private javax.swing.JTextField IdPay;
    private javax.swing.JTextField IdPerms;
    private javax.swing.JTextField JOB_PAYjTextField13;
    private javax.swing.JTextField JOB_PERMSjTextField20;
    private javax.swing.JTextField NAME_PAYjTextField11;
    private javax.swing.JTextField NAME_PERMSjTextField18;
    private javax.swing.JTable PAYjTable2;
    private javax.swing.JTable PERMSjTable3;
    private javax.swing.JButton PRINT_PAYjButton9;
    private javax.swing.JButton PRINT_PERMSjButton11;
    private javax.swing.JTextField SALARY_PAYjTextField14;
    private javax.swing.JTextField STOTAL_PAYjTextField17;
    private javax.swing.JTextField TYPE_PERMSjTextField21;
    private javax.swing.JButton UPDATEjButton5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelPay;
    private javax.swing.JPanel jPanelPermis;
    private javax.swing.JPanel jPanelStaff;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedStaff;
    public javax.swing.JTable jTableresgistrar;
    private javax.swing.JTextField jTextFieldCargoEmpleados;
    private javax.swing.JTextField jTextFieldContratacionEmpleados;
    private javax.swing.JTextField jTextFieldCorreoEmpleados;
    private javax.swing.JTextField jTextFieldDireccionEmpleados;
    private javax.swing.JTextField jTextFieldEntradaEmpleados;
    private javax.swing.JTextField jTextFieldIDEmpleados;
    private javax.swing.JTextField jTextFieldNombreEmpleados;
    private javax.swing.JTextField jTextFieldSalidaEmpleados;
    private javax.swing.JTextField jTextFieldTelefonoEmpleados;
    private javax.swing.JTextField txtBuscarE;
    // End of variables declaration//GEN-END:variables
private void LimpiarEmpleados() {

        jTextFieldNombreEmpleados.setText("");
        jTextFieldIDEmpleados.setText("");
        jTextFieldCorreoEmpleados.setText("");
        jTextFieldDireccionEmpleados.setText("");
        jTextFieldTelefonoEmpleados.setText("");
        jTextFieldCargoEmpleados.setText("");
        jTextFieldEntradaEmpleados.setText("");
        jTextFieldSalidaEmpleados.setText("");
        jTextFieldContratacionEmpleados.setText("");

    }

    private void LimpiarNomina() {

        NAME_PAYjTextField11.setText("");
        ID_PAYjTextField12.setText("");
        JOB_PAYjTextField13.setText("");
        SALARY_PAYjTextField14.setText("");
        COM_PAYjTextField15.setText("");
        BONUS_PAYjTextField16.setText("");
        STOTAL_PAYjTextField17.setText("");

    }

    private void LimpiarPermisos() {

        NAME_PERMSjTextField18.setText("");
        ID_PERMSTextField19.setText("");
        JOB_PERMSjTextField20.setText("");
        TYPE_PERMSjTextField21.setText("");
        DESCRjTextField22.setText("");

    }
}
